services:

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgres-postgis-pgvector
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-propertydb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: django-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_data:/app/media
    depends_on:
      - db

volumes:
  pgdata:
  media_data: